"""add field likes to posts table

Revision ID: 143f22f46bf0
Revises: 3b06c16093f5
Create Date: 2026-09-29 01:24:51.910736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143f22f46bf0'
down_revision: Union[str, Sequence[str], None] = '3b06c16093f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('pst_likes', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'pst_likes')
    # ### end Alembic commands ###
