"""initial schema

Revision ID: 3b06c16093f5
Revises: 
Create Date: 2026-09-29 01:09:00.463306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b06c16093f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('usr_id', sa.Integer(), nullable=False),
    sa.Column('usr_name', sa.String(length=50), nullable=False),
    sa.Column('usr_password_hash', sa.String(length=200), nullable=False),
    sa.Column('usr_email', sa.String(length=120), nullable=False),
    sa.Column('usr_image_path', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('usr_id'),
    sa.UniqueConstraint('usr_email'),
    sa.UniqueConstraint('usr_name'),
    sa.UniqueConstraint('usr_password_hash')
    )
    op.create_index(op.f('ix_users_usr_id'), 'users', ['usr_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('prt_id', sa.Integer(), nullable=False),
    sa.Column('prt_user_id', sa.Integer(), nullable=False),
    sa.Column('prt_token_hash', sa.String(length=64), nullable=False),
    sa.Column('prt_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prt_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prt_user_id'], ['users.usr_id'], ),
    sa.PrimaryKeyConstraint('prt_id'),
    sa.UniqueConstraint('prt_token_hash')
    )
    op.create_index(op.f('ix_password_reset_tokens_prt_id'), 'password_reset_tokens', ['prt_id'], unique=False)
    op.create_table('posts',
    sa.Column('pst_id', sa.Integer(), nullable=False),
    sa.Column('pst_title', sa.String(length=100), nullable=False),
    sa.Column('pst_content', sa.Text(), nullable=False),
    sa.Column('pst_user_id', sa.Integer(), nullable=False),
    sa.Column('pst_date_posted', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pst_user_id'], ['users.usr_id'], ),
    sa.PrimaryKeyConstraint('pst_id')
    )
    op.create_index(op.f('ix_posts_pst_id'), 'posts', ['pst_id'], unique=False)
    op.create_index(op.f('ix_posts_pst_user_id'), 'posts', ['pst_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_pst_user_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_pst_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_password_reset_tokens_prt_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_users_usr_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
